version: '3.8'

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus_new
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana
    container_name: grafana_new
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=Omen15@6631
    networks:
      - monitoring
    depends_on:
      - prometheus
  docker-exporter:
    image: prom/docker-exporter
    ports:
      - "9104:9104"
    restart: unless-stopped
networks:
  monitoring:
    driver: bridge
