networks:
  app-net:
    driver: bridge

services:
  sb-app:
    build: .
    container_name: "docker-app"
    ports:
      - 5000:5000
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/docker-db
    networks:
      - app-net

  mongodb:
    image: mongo:latest
    container_name: "mongodbb"
    ports:
      - 27070:27017
    networks:
      - app-net
