version: '3'
services:
  mongo-db:
    image: mongo:4.4
    container_name: docker-compose-mongo-db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    networks:
      - my-network

  spring-boot-app:
    image: omnia462/courzello
    container_name: docker-compose-spring-boot
    ports:
      - "8088:8090"
    depends_on:
      - mongo-db
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://root:root@docker-compose-mongo-db:27017/courzello?authSource=admin
    networks:
      - my-network

networks:
  my-network:
