pipeline {
    agent any

    tools {
        maven 'M2_HOME' // Ensure 'M2_HOME' matches the Maven installation name in Jenkins
    }

    stages {
        stage('Checkout') {
            steps {
                // Cloning the Git repository from the 'yosra' branch
                git branch: 'yosra', url: 'https://github.com/Si-aymen/Courzelo-Devops.git'
            }
        }

        

        stage('Build') {
            steps {
                dir('backendPidev') { // Adjust if needed based on directory structure
                    sh 'mvn clean install'
                }
            }
        }
      
        stage('Test') {
                   steps {
                       dir('backendPidev') { // Adjust if needed
                           sh 'mvn test'
                       }
                       // Archive test results for JUnit
                       junit 'backendPidev/target/surefire-reports/*.xml'
                   }
               }

      
      stage('SonarQube Analysis') {
            steps {
                dir('backendPidev') {
                    script {
                        withSonarQubeEnv('sonar courZelo') {
                            sh '''
                                mvn sonar:sonar \
                                -Dsonar.projectKey=Courzello \
                                -Dsonar.host.url=http://192.168.33.10:9000 \
                                -Dsonar.login=admin \
                                -Dsonar.password=Aymenrahali@6631 \
                                -Dmaven.test.skip=true
                            '''
                        }
                    }
                }
            }
        }
        stage ('Nexus'){
            steps {
                dir('backendPidev') {
                sh 'mvn deploy ' 
                }
            }
        }   
    }

    post {
        success {
            echo 'Build and tests succeeded!'
        }
        failure {
            echo 'Build failed. Please check the logs.'
        }
    }
}
